### ISSUE TITLE
Can't start the bot

### ISSUE THREAD

**Issue by Minnona** [fjaros/wowchat#106]
Hey, getting this error in windows:

```
C:\Users\minn\Desktop\wowchat>java -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dlogback.configurationFile=logback.xml -jar wowchat.jar wowchat.conf
12:09:45.246 INFO  wowchat.WoWChat$ - Running WoWChat - v1.3.8
Exception in thread "main" com.typesafe.config.ConfigException$Missing: wowchat.conf: 2: No configuration setting found for key 'token'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:157)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:175)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:194)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:251)
        at wowchat.common.WowChatConfig$.apply(Config.scala:50)
        at wowchat.WoWChat$.main(WoWChat.scala:26)
        at wowchat.WoWChat.main(WoWChat.scala)

C:\Users\minn\Desktop\wowchat>pause
Press any key to continue . . .
```

**Comment by Minnona** [comment]
Thought I had to leave ${?}, now works
