### ISSUE TITLE
netty related exception for qualified who queries

### ISSUE THREAD

**Issue by Road-block** [fjaros/wowchat#14]
Far as I can tell the following exception only happens with `?who term`  
When `term` is not found online.  

```
WARN  i.n.c.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IndexOutOfBoundsException: readerIndex(8) + length(4) exceeds writerIndex(8): PooledUnsafeDirectByteBuf(ridx: 8, widx: 8, cap: 8)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
        at io.netty.buffer.AbstractByteBuf.readIntLE(AbstractByteBuf.java:794)
        at wowchat.game.GamePacketHandler.$anonfun$handle_SMSG_WHO$1(GamePacketHandler.scala:630)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:155)
        at wowchat.game.GamePacketHandler.handle_SMSG_WHO(GamePacketHandler.scala:627)
        at wowchat.game.GamePacketHandler.channelParse(GamePacketHandler.scala:237)
        at wowchat.game.GamePacketHandler.channelRead(GamePacketHandler.scala:218)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

**Comment by Road-block** [comment]
I'm not fully conversant in Java/Java network libraries but this is the closest I've found of a relevant issue.  
https://stackoverflow.com/questions/29067539/netty-weird-indexoutofboundsexception-readerindex-length-exceeds-writerindex

**Comment by Road-block** [comment]
I was looking for a `Vanilla` label to tag the issue but didn't find one.  
This is with regards to 1.12.

**Comment by fjaros** [comment]
Got it. I'll take a look into it. Looks like an easy issue to fix.

**Comment by fjaros** [comment]
Project isn't big enough for label tags ;) The code already has checks for not found online: https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/game/GamePacketHandler.scala#L624

So it seems rather interesting - maybe the particular server you're playing on is sending a botched WHO response (sending that it has count of users but doesn't send payload). Can you send me a debug log? In logback.xml change:
    <logger name="wowchat.game.GamePacketDecoder" level="DEBUG" />
    <logger name="wowchat.game.GamePacketEncoder" level="DEBUG" />
it will start printing packet dumps into the log file. Just the section where you send/receive WHO is sufficient.

**Comment by fjaros** [comment]
Actually what is probably happening is that the server sends a big "match count" but no "display count" . I probably should be using the display count as an indicator of returned results rather than the full match count. But i'd like to see the log to confirm.

**Comment by Road-block** [comment]
Will do.  
Several servers send the full faction or server pop count back on /who queries.  
Similar to what an .s info command would return (minus the logged in but not in world count)

**Comment by Road-block** [comment]
[wowchat.log.zip](https://github.com/fjaros/wowchat/files/2881897/wowchat.log.zip)

**Comment by fjaros** [comment]
Perfect, thanks so much!
```
20:15:19.411 DEBUG w.g.GamePacketDecoder - RECV PACKET: 0063 - 00 00 00 00 BA 00 00 00
```
it is indeed the case that display count is 0 but match count is 186 (0xBA) . so the bot should just use the display count for the WHO message parsing https://github.com/fjaros/wowchat/blob/master/src/main/scala/wowchat/game/GamePacketHandler.scala#L624 . Funnily in the MoP implementation, there is no such thing as match count to begin with, but only display count. I can patch this tonight. But of course feel free to make the contribution :)

**Comment by fjaros** [comment]
Fixed in https://github.com/fjaros/wowchat/commit/f743e438525a81a09a6816dcb23fc8691fe2531e and patched release file.
