### ISSUE TITLE
java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by yutsuku** [fjaros/wowchat#44]
Recently the instance I host started to disconnect from game world very often (few times per hour). Minimum interval I've noticed was around 5 minutes. Quick internet search suggests that this may be netty library fault. Any suggestions?

Runtime information
```
java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)
```

Common error in question
```
13:52:36.996 WARN  i.n.c.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:283)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:236)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:226)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:382)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:844)
13:52:37.004 INFO  wowchat.WoWChat$ - Disconnected from server! Reconnecting in 10 seconds...
13:52:47.006 INFO  w.r.RealmConnector - Connecting to realm server logon.dalaran-realmlist.org:3724
13:52:57.185 ERROR w.r.RealmConnector - Failed to connect to realm server! io.netty.channel.ConnectTimeoutException: connection timed out: logon.dalaran-realmlist.org/195.154.184.98:3724
13:52:57.187 INFO  wowchat.WoWChat$ - Disconnected from server! Reconnecting in 10 seconds...
13:53:07.188 INFO  w.r.RealmConnector - Connecting to realm server logon.dalaran-realmlist.org:3724
13:53:10.411 INFO  w.r.RealmPacketHandlerTBC - Connected! Sending account login information...
13:53:17.420 INFO  w.r.RealmPacketHandlerTBC - Successfully logged into realm server. Looking for realm Algalon - Main Realm
13:53:17.537 INFO  w.g.GameConnector - Connecting to game server Algalon - Main Realm (37.187.164.32:8086)
13:53:17.669 INFO  w.g.GamePacketHandlerWotLK - Connected! Authenticating...
13:53:18.238 INFO  w.g.GamePacketHandlerWotLK - Successfully logged in!
13:53:18.479 INFO  w.g.GamePacketHandlerWotLK - Logging in with character MyBotName
13:53:18.705 INFO  w.g.GamePacketHandlerWotLK - Successfully joined the world!
```

**Comment by fjaros** [comment]
This happens when remote server goes down/connection is terminated. As you see the bot will try to automatically reconnect.
