### ISSUE TITLE
No configuration setting found for key 'discord'

### ISSUE THREAD

**Issue by siadrian** [fjaros/wowchat#46]
Hi,
I updated with the latest version and right now I get this error when I run it from the terminal:

bash run.sh
14:13:16.663 INFO  wowchat.WoWChat$ - Running WoWChat - v1.3.4
Exception in thread "main" com.typesafe.config.ConfigException$Missing: system properties: No configuration setting found for key 'discord'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
	at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
	at wowchat.common.WowChatConfig$.apply(Config.scala:38)
	at wowchat.WoWChat$.main(WoWChat.scala:26)
	at wowchat.WoWChat.main(WoWChat.scala)

I'm running wowchat on a raspi zero w with raspbian installed. I ran it before this update and it worked, didn't get this error.

**Comment by siadrian** [comment]
also looks like you have dos line endings in run.sh because running it says bad interpreter, finds some ^M
