### ISSUE TITLE
Issue with errors.

### ISSUE THREAD

**Issue by AllyPallies** [fjaros/wowchat#54]
Hi there im trying to get this to work on my server thats a 7.0.3 (i understand its not supported but im trying to see if i can get it working.)

the error im getting is 
java -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dlogback.configurationFile=logback.xml -jar wowchat.jar wowchat.conf
21:53:15.585 INFO  wowchat.WoWChat$ - Running WoWChat - v1.3.7
Exception in thread "main" com.typesafe.config.ConfigException$Parse: wowchat.conf: 41: Expecting close brace } or a comma, got '@' (Reserved character '@' is not allowed outside quotes) (if you intended '@' (Reserved character '@' is not allowed outside quotes) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:528)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseValue(ConfigDocumentParser.java:247)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:458)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
        at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:262)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:250)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:301)
        at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:739)
        at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:753)
        at wowchat.common.WowChatConfig$.apply(Config.scala:33)
        at wowchat.WoWChat$.main(WoWChat.scala:26)
        at wowchat.WoWChat.main(WoWChat.scala)
Would you be able to either assist on this or fix this for me? i understand you might not be actively working on this but any assistance would be amazing!

**Comment by fjaros** [comment]
Hi there. The error message is pretty clear. You should read it and fix your configuration.

That said, I applaud your effort to try to make 7.0.3 work. You'll have to rewrite all of the realm and game server communication code. Good luck!
