### ISSUE TITLE
support vanilla version ealier than 1.12

### ISSUE THREAD

**Issue by den13501** [fjaros/wowchat#63]
I look into code, theere is no hash for the ealier vesion than 5875, how to make wowchat to support these game client?
thanks..

```
    {5875,  1, 12, 1, ' ',
    { { 0x95, 0xED, 0xB2, 0x7C, 0x78, 0x23, 0xB3, 0x63, 0xCB, 0xDD, 0xAB, 0x56, 0xA3, 0x92, 0xE7, 0xCB, 0x73, 0xFC, 0xCA, 0x20 } },
    { { 0x8D, 0x17, 0x3C, 0xC3, 0x81, 0x96, 0x1E, 0xEB, 0xAB, 0xF3, 0x36, 0xF5, 0xE6, 0x67, 0x5B, 0x10, 0x1B, 0xB5, 0x13, 0xE5 } },
    },
    {5464,  1, 11, 2, ' ', {{}}, {{}}},
    {5302,  1, 10, 2, ' ', {{}}, {{}}},
    {5086,  1, 9, 4,  ' ', {{}}, {{}}},
    {4878,  1, 8, 4,  ' ', {{}}, {{}}},
    {4695,  1, 7, 1,  ' ', {{}}, {{}}},
    {4620,  1, 6, 3,  ' ', {{}}, {{}}},
    {4565,  1, 6, 2,  ' ', {{}}, {{}}},
    {4544,  1, 6, 1,  ' ', {{}}, {{}}},
    {0,     0, 0, 0,  ' ', {{}}, {{}}}  
```

**Comment by den13501** [comment]
the log show as below:
```
java.lang.IllegalArgumentException: Build 1.7.1 not supported!

	at wowchat.common.WowChatConfig$.$anonfun$getBuild$1(Config.scala:92)

	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)

	at scala.Option.getOrElse(Option.scala:189)

	at wowchat.common.WowChatConfig$.getBuild$lzycompute(Config.scala:79)

	at wowchat.common.WowChatConfig$.getBuild(Config.scala:77)

	at wowchat.realm.RealmPacketHandler.channelActive(RealmPacketHandler.scala:69)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)

	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)

	at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)

	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)

	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)

	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)

	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)

	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)

	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)

	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)

	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

	at java.lang.Thread.run(Thread.java:748)
```
