### ISSUE TITLE
[request]how to make bot support 1.7.1

### ISSUE THREAD

**Issue by den13501** [fjaros/wowchat#64]
I edit the wowchat.conf
```
# Global WoW Configurations
wow {
  # You MUST keep this as Mac on Warden (anticheat) enabled servers. Windows Warden is not implemented.
  # Only reason to change this is for servers on which Mac login is not working and also which have Warden disabled.
  platform=Mac

  # Whether to treat server's MotD message as a server SYSTEM message.
  enable_server_motd=1

  version=1.7.1
```

however, the log show as below:
```
java.lang.IllegalArgumentException: Build 1.7.1 not supported!

	at wowchat.common.WowChatConfig$.$anonfun$getBuild$1(Config.scala:92)

	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)

	at scala.Option.getOrElse(Option.scala:189)

	at wowchat.common.WowChatConfig$.getBuild$lzycompute(Config.scala:79)

	at wowchat.common.WowChatConfig$.getBuild(Config.scala:77)

	at wowchat.realm.RealmPacketHandler.channelActive(RealmPacketHandler.scala:69)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)

	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)

	at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)

	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)

	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)

	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)

	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)

	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)

	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)

	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)

	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

	at java.lang.Thread.run(Thread.java:748)
```

_Originally posted by @den13501 in https://github.com/fjaros/wowchat/issues/63#issuecomment-1003259289_

**Comment by fjaros** [comment]
Sorry for the late reply. In https://github.com/fjaros/wowchat/commit/d06637460f82187d074e2c569853617724df61e8 , I've added support automatically for some versions supported by vmangos project , including the build number and build hashes. However I did not test that the bot is successfully able to login or send messages on these old builds as I don't have a testing environment. But feel free to try.

**Comment by den13501** [comment]
> Sorry for the late reply. In [d066374](https://github.com/fjaros/wowchat/commit/d06637460f82187d074e2c569853617724df61e8) , I've added support automatically for some versions supported by vmangos project , including the build number and build hashes. However I did not test that the bot is successfully able to login or send messages on these old builds as I don't have a testing environment. But feel free to try.

Hi fjaros, thanks for your effort to make it support older version of vanilla wow.
Unfortunately, chatbot still cannot logon my test 1.7.1 server, below is my screenshot, hope I can do a favor...
![圖片](https://user-images.githubusercontent.com/58270741/156834418-d3be28dc-b2f5-4f1d-b2e2-88259d9a45ec.png)

**Comment by fjaros** [comment]
looks like the realm server is not even sending back a response to the login packet. you should first analyze the network traffic. you can have the bot print out the network packets by changing the GamePacketEncoder and GamePacketDecoder logging to "DEBUG" value in https://github.com/fjaros/wowchat/blob/master/src/main/resources/logback.xml

if indeed the communication protocol is different for 1.7.1 than 1.12.1 then you will have to implement these differences on your own.

**Comment by den13501** [comment]
Hi sir, thanks for your guide, I enable debug logging to record packets

this is 1.7.1 ,server did not respond bot's request
![圖片](https://user-images.githubusercontent.com/58270741/156865956-a044b7f3-3b76-403d-a094-df138280ac68.png)

and this is 1.12.1 , connect successfully
![圖片](https://user-images.githubusercontent.com/58270741/156866007-7f207bfb-6a3b-4c0f-9bba-0b56b259d6a2.png)

however, I don't know what protocol different between these two..

**Comment by fjaros** [comment]
unfortunately that is something you will have to figure out on your own as the "vanilla" implementation was built specifically for the 1.12.1 client. you'll have to read the code of the server to see what packet and payload in that packet it expects and then modify wowchat code to send that instead.

To get you started, here is where vmangos handles the 0000 or "logon challenge" packet: https://github.com/vmangos/core/blob/development/src/realmd/AuthSocket.cpp#L316

good luck!
