### ISSUE TITLE
No configuration setting found for key 'token'

### ISSUE THREAD

**Issue by jamesilver** [fjaros/wowchat#73]
I set it up as it is explained and when i run it this error pops in cmd.

23:50:25.368 INFO  wowchat.WoWChat$ - Running WoWChat - v1.3.8
Exception in thread "main" com.typesafe.config.ConfigException$Missing: wowchat.conf: 2: No configuration setting found for key 'token'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:157)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:175)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:194)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:251)
        at wowchat.common.WowChatConfig$.apply(Config.scala:50)
        at wowchat.WoWChat$.main(WoWChat.scala:26)
        at wowchat.WoWChat.main(WoWChat.scala)

**Comment by fjaros** [comment]
Look at the readme on how to set up the configuration. Make sure in wowchat.conf, you have 
```
token=discordtokenhere
```
