### ISSUE TITLE
Disconnect from server

### ISSUE THREAD

**Issue by Dumpf** [fjaros/wowchat#82]
Hi! Can you help me? I set everything up as you have in the description. Everything works as it should. But I have a constant reconnect to the server (The character enters the world and can immediately, or maybe after 20 minutes, exit and re-enter). Is it possible to fix it somehow?
18:26:49.371 INFO wowchat.WoWChat$ - Disconnected from server! Reconnecting in 10 seconds ...
Can send any commands to the account so that it is not afk? for example, sit down-stand up or jump. How to implement it? Although I'm not sure if it's because of the afc...

**Comment by Dumpf** [comment]
21:14:03.223 INFO  w.g.GamePacketHandlerWotLK - Joined Channel: [Cast]
21:14:03.224 INFO  w.g.GamePacketHandlerWotLK - Joined Channel: [Chadwarriors]
21:14:30.478 WARN  i.n.c.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Удаленный хост принудительно разорвал существующее подключение
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:258)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
21:14:48.869 INFO  w.d.Discord - Discord->WoW(Guild) [Алексей-влг]: -
21:14:55.692 INFO  wowchat.WoWChat$ - Disconnected from server! Reconnecting in 10 seconds...

**Comment by Dumpf** [comment]
21:23:56.639 INFO  wowchat.WoWChat$ - Disconnected from server! Reconnecting in 10 seconds...
21:27:10.923 INFO  w.r.RealmConnector - Connecting to realm server 37.230.118.5:9643
21:27:12.056 INFO  w.r.RealmPacketHandlerTBC - Connected! Sending account login information...
21:27:12.391 INFO  w.r.RealmPacketHandlerTBC - Successfully logged into realm server. Looking for realm Sirus x5 - 3.3.5a+
21:27:12.709 INFO  w.g.GameConnector - Connecting to game server Sirus x5 - 3.3.5a+ (31.135.8.49:7777)
21:27:12.937 INFO  w.g.GamePacketHandlerWotLK - Connected! Authenticating...
21:27:13.683 INFO  w.g.GamePacketHandlerWotLK - Successfully logged in!
21:27:14.191 INFO  w.g.GamePacketHandlerWotLK - Logging in with character Wowchat
21:27:14.969 INFO  w.g.GamePacketHandlerWotLK - Successfully joined the world!
21:27:14.973 INFO  w.g.GamePacketHandlerWotLK - Joining channel General - Orgrimmar
21:27:14.977 INFO  w.g.GamePacketHandlerWotLK - Joining channel Trade - City
21:27:14.980 INFO  w.g.GamePacketHandlerWotLK - Joining channel Cast
21:27:14.991 INFO  w.g.GamePacketHandlerWotLK - Joining channel Chadwarriors
21:27:32.540 INFO  w.g.GamePacketHandlerWotLK - Joined Channel: [General - ]
21:27:32.541 INFO  w.g.GamePacketHandlerWotLK - Joined Channel: [Cast]
21:27:32.545 INFO  w.g.GamePacketHandlerWotLK - Joined Channel: [Chadwarriors]
21:28:15.060 INFO  wowchat.WoWChat$ - Disconnected from server! Reconnecting in 10 seconds...

**Comment by fjaros** [comment]
the disconnect happens too quickly to be an afk problem. I will have to look into this server in particular to see what is happening. don't have any info for you right now.

**Comment by Dumpf** [comment]
Good! I will wait and hope that you can help me fix this problem. Server: https://sirus.su

**Comment by Dumpf** [comment]
realmlist
151.80.20.84:9643  or 37.230.118.5:9643

**Comment by fjaros** [comment]
I can reproduce it but I don't know why it's happening. On this server you also have to run their custom patched version of wow which doesn't work on my computer (crashes on start). Sorry! Maybe reach out to the server devs to see why you're being disconnected.

**Comment by Dumpf** [comment]
Yes, there are constant updates of the game client on this server. Wowchat, as I understand it, runs the standard 3.3.5 ... Is it possible to prescribe what to connect to the game using these files E:\Games\WorldOfWarcraft\World Warcraft Sirus\run.exe
