### ISSUE TITLE
An exceptionCaught() event was fired

### ISSUE THREAD

**Issue by excelyte** [fjaros/wowchat#90]
Hi! I don't understand what the problem is. I have no programming skills, but I did everything according to the instructions.

```
C:\Downloads\wowchat>chcp 65001
Active code page: 65001

C:\Downloads\wowchat>java -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dlogback.configurationFile=logback.xml -jar wowchat.jar wowchat.conf
17:46:14.794 INFO  wowchat.WoWChat$ - Running WoWChat - v1.3.8
17:46:16.770 INFO  wowchat.WoWChat$ - Connecting to Discord...
17:46:17.594 INFO  n.d.jda.api.JDA - Login Successful!
17:46:18.079 INFO  n.d.j.i.r.WebSocketClient - Connected to WebSocket
17:46:18.395 INFO  n.d.jda.api.JDA - Finished Loading!
17:46:18.433 INFO  w.r.RealmConnector - Connecting to realm server logon.turtle-wow.org:3724
17:46:18.736 INFO  w.r.RealmPacketHandler - Connected! Sending account login information...
17:46:18.758 WARN  i.n.c.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
        at wowchat.common.WowChatConfig$.getBuild$lzycompute(Config.scala:79)
        at wowchat.common.WowChatConfig$.getBuild(Config.scala:77)
        at wowchat.realm.RealmPacketHandler.channelActive(RealmPacketHandler.scala:89)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
        at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)```

**Comment by fjaros** [comment]
Yeah Turtle wow unfortunately did not work out of the box, but I just added a fix for it by allowing you to set different build numbers for the realm server and the game server. Re-download the release zip file.
You will need to set the following in your configuration:
```
  version=1.12.1
  realm_build=7060
  game_build=5875
```
realm_build will change with each new version they release
