### ISSUE TITLE
exceptionCaught(): IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Loken-coolguy** [fjaros/wowchat#96]
Hello, 

I continue to get this error when attempting to connect to the server. It seems to be stuck on the Authenticating step. I tried modifying the .conf file to have Mac/Windows, and also tried adding Realm_Build and others that were modified with Turtle WoW, but no success. Not sure what I am doing wrong, any help would be appreciated.

01:59:57.729 INFO  w.g.GamePacketHandlerCataclysm15595 - Connected! Authenticating...
01:59:58.296 WARN  i.n.c.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IndexOutOfBoundsException: readerIndex(0) + length(16) exceeds writerIndex(2): PooledUnsafeDirectByteBuf(ridx: 0, widx: 2, cap: 2)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1428)
	at io.netty.buffer.AbstractByteBuf.skipBytes(AbstractByteBuf.java:971)
	at wowchat.game.GamePacketHandlerCataclysm15595.parseAuthResponse(GamePacketHandlerCataclysm15595.scala:105)
	at wowchat.game.GamePacketHandler.handle_SMSG_AUTH_RESPONSE(GamePacketHandler.scala:294)
	at wowchat.game.GamePacketHandler.channelParse(GamePacketHandler.scala:239)
	at wowchat.game.GamePacketHandlerTBC.channelParse(GamePacketHandlerTBC.scala:38)
	at wowchat.game.GamePacketHandlerCataclysm15595.channelParse(GamePacketHandlerCataclysm15595.scala:17)
	at wowchat.game.GamePacketHandler.channelRead(GamePacketHandler.scala:230)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
01:59:58.302 INFO  wowchat.WoWChat$ - Disconnected from server! Reconnecting in 10 seconds...

I've uploaded my config file here (I renamed to .txt just so it would upload)
[wowchat.conf.txt](https://github.com/fjaros/wowchat/files/11252978/wowchat.conf.txt)

Thank you, appreciate the help

**Comment by fjaros** [comment]
Fixed in https://github.com/fjaros/wowchat/commit/9926564431077b86dfb4a1d8207fd9939919361f . Please re-download the release zip file and try again. Thanks for the report!
